"""
FastAPI Backend Template for AI SaaS Apps
Customize prompts and models per app type.
"""

import os
from datetime import datetime
from fastapi import FastAPI, HTTPException, Depends, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
import stripe
from dotenv import load_dotenv
from contextlib import asynccontextmanager

from config import settings
from services.claude import ClaudeService
from services.database import Database
from services.stripe_service import StripeService
from routes import generate, payments
from utils.logging import setup_logging

# Load environment
load_dotenv()

# Setup logging
logger = setup_logging()

# Initialize services
claude_service = ClaudeService(settings.ANTHROPIC_API_KEY)
stripe_service = StripeService(settings.STRIPE_SECRET_KEY)
db = Database(settings.SUPABASE_URL, settings.SUPABASE_ANON_KEY)

@asynccontextmanager
async def lifespan(app: FastAPI):
    # Startup
    logger.info("Starting AI Micro Course Creator...")
    await db.connect()
    yield
    # Shutdown
    logger.info("Shutting down...")
    await db.disconnect()

app = FastAPI(
    title="AI Micro Course Creator",
    description="Auto-generated by Hermes Agent",
    version="1.0.0",
    lifespan=lifespan
)

# CORS - allow iOS app
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Restrict to your app's domain
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Include routers
app.include_router(generate.router, prefix="/api/v1", tags=["generate"])
app.include_router(payments.router, prefix="/api/v1", tags=["payments"])

@app.get("/health")
async def health_check():
    """Health check endpoint"""
    return {"status": "ok", "timestamp": datetime.utcnow().isoformat()}

@app.exception_handler(Exception)
async def global_exception_handler(request: Request, exc: Exception):
    logger.error(f"Unhandled exception: {exc}", exc_info=True)
    return JSONResponse(
        status_code=500,
        content={"detail": "Internal server error"}
    )

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=int(os.getenv("PORT", 8000)))
